import { Router, Request, Response, NextFunction } from 'express';
import os from 'os';
import crypto from 'crypto';

export const chatgptConnectorRouter = Router();

// ----------------------------------------------------
// OAUTH 2.0 & AUTHENTICATION STATE (In-Memory Safe Store)
// ----------------------------------------------------

// Default OAuth credentials created for ChatGPT Custom Actions / MCP
const OAUTH_CLIENT_ID = process.env.CHATGPT_OAUTH_CLIENT_ID || 'mido-ai-client';
const OAUTH_CLIENT_SECRET = process.env.CHATGPT_OAUTH_CLIENT_SECRET || 'mido_sec_chatgpt_live';

// Master Mido Connector API Key (generated by Mido AI, independent of third-party credentials)
let currentMidoApiKey = process.env.MIDO_CONNECTOR_API_KEY || 'mido_key_live_' + crypto.randomBytes(8).toString('hex');

// OAuth Authorization codes map: code -> metadata
interface AuthCodeRecord {
  code: string;
  clientId: string;
  redirectUri: string;
  state?: string;
  scope?: string;
  codeChallenge?: string;
  codeChallengeMethod?: string;
  expiresAt: number;
}
const authCodes = new Map<string, AuthCodeRecord>();

// Active OAuth Access Tokens map: token -> metadata
interface AccessTokenRecord {
  token: string;
  clientId: string;
  scope: string;
  createdAt: number;
  expiresAt: number;
  refreshToken?: string;
}
const activeTokens = new Map<string, AccessTokenRecord>();

// Pre-seed an active token for seamless local / direct MCP invocation
const DEFAULT_SEED_TOKEN = 'mido_oauth_live_' + crypto.randomBytes(12).toString('hex');
activeTokens.set(DEFAULT_SEED_TOKEN, {
  token: DEFAULT_SEED_TOKEN,
  clientId: OAUTH_CLIENT_ID,
  scope: 'mido:read mido:propose',
  createdAt: Date.now(),
  expiresAt: Date.now() + 30 * 24 * 3600 * 1000 // 30 days
});

// Safe in-memory store for proposals submitted by ChatGPT (pending user approval)
export interface ChatGPTProposal {
  id: string;
  timestamp: string;
  title: string;
  category: 'feature' | 'refactor' | 'bugfix' | 'performance' | 'ui';
  description: string;
  suggestedCodeSnippet?: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
}

const pendingProposals: ChatGPTProposal[] = [
  {
    id: 'prop_welcome_sample',
    timestamp: new Date().toISOString(),
    title: 'Initial ChatGPT Connector Handshake',
    category: 'feature',
    description: 'ChatGPT secure connector initialized and ready for authenticated inspection and authorized collaboration.',
    reason: 'System initialization',
    status: 'pending'
  }
];

// Helper to determine the public server URL
function getServerUrl(req: Request): string {
  // Respect forwarded headers if running behind Cloud Run / reverse proxy
  const proto = (req.headers['x-forwarded-proto'] as string) || req.protocol || 'http';
  const host = (req.headers['x-forwarded-host'] as string) || req.get('host') || 'localhost:3000';
  return `${proto}://${host}`;
}

// ----------------------------------------------------
// SECURITY: OAuth & Token Authentication Middleware
// ----------------------------------------------------
export function verifyConnectorAuth(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.headers.authorization;
  const customKeyHeader = req.headers['x-connector-key'];
  const queryToken = req.query.token as string | undefined;

  let providedToken = '';

  if (authHeader && authHeader.startsWith('Bearer ')) {
    providedToken = authHeader.slice(7).trim();
  } else if (typeof customKeyHeader === 'string') {
    providedToken = customKeyHeader.trim();
  } else if (queryToken) {
    providedToken = queryToken.trim();
  }

  if (!providedToken) {
    res.setHeader('WWW-Authenticate', 'Bearer realm="mido-ai-connector", error="invalid_token"');
    return res.status(401).json({
      error: 'Unauthorized',
      code: 'MISSING_TOKEN',
      message: 'Access denied: Valid OAuth Bearer Token or Mido AI Connector Key is required.',
      help: 'Authenticate via OAuth 2.0 (/oauth/authorize) or provide header "Authorization: Bearer <TOKEN>".',
      oauthDiscovery: '/.well-known/oauth-authorization-server',
      openapi: '/api/openapi.json'
    });
  }

  // Check 1: Is it a valid OAuth Access Token?
  const oauthTokenRecord = activeTokens.get(providedToken);
  if (oauthTokenRecord) {
    if (Date.now() > oauthTokenRecord.expiresAt) {
      activeTokens.delete(providedToken);
      res.setHeader('WWW-Authenticate', 'Bearer realm="mido-ai-connector", error="token_expired"');
      return res.status(401).json({
        error: 'Unauthorized',
        code: 'TOKEN_EXPIRED',
        message: 'Your OAuth Access Token has expired. Please refresh the token via /oauth/token.'
      });
    }
    // Token is valid!
    (req as any).connectorAuth = { type: 'oauth', ...oauthTokenRecord };
    return next();
  }

  // Check 2: Is it the active Mido Connector API Key?
  if (providedToken === currentMidoApiKey || providedToken === DEFAULT_SEED_TOKEN) {
    (req as any).connectorAuth = { type: 'apiKey', token: providedToken };
    return next();
  }

  // Invalid token
  res.setHeader('WWW-Authenticate', 'Bearer realm="mido-ai-connector", error="invalid_token"');
  return res.status(401).json({
    error: 'Unauthorized',
    code: 'INVALID_TOKEN',
    message: 'Access denied: The provided token is invalid or has been revoked.',
    help: 'Configure OAuth in ChatGPT using /oauth/authorize and /oauth/token or check the Mido AI settings.'
  });
}

// ----------------------------------------------------
// 1. OAUTH 2.0 RFC 8414 DISCOVERY ENDPOINTS
// ----------------------------------------------------
const handleOauthDiscovery = (req: Request, res: Response) => {
  const serverUrl = getServerUrl(req);
  res.json({
    issuer: serverUrl,
    authorization_endpoint: `${serverUrl}/oauth/authorize`,
    token_endpoint: `${serverUrl}/oauth/token`,
    revocation_endpoint: `${serverUrl}/oauth/revoke`,
    userinfo_endpoint: `${serverUrl}/api/connector/status`,
    response_types_supported: ['code'],
    grant_types_supported: ['authorization_code', 'refresh_token', 'client_credentials'],
    token_endpoint_auth_methods_supported: ['client_secret_post', 'client_secret_basic', 'none'],
    scopes_supported: ['mido:read', 'mido:propose'],
    code_challenge_methods_supported: ['S256', 'plain'],
    service_documentation: `${serverUrl}/api/openapi.json`
  });
};

chatgptConnectorRouter.get('/.well-known/oauth-authorization-server', handleOauthDiscovery);
chatgptConnectorRouter.get('/.well-known/openid-configuration', handleOauthDiscovery);

// ----------------------------------------------------
// 2. OAUTH 2.0 AUTHORIZATION ENDPOINT (GET & POST)
// Renders Mobile-Friendly Mido AI Consent UI for ChatGPT
// ----------------------------------------------------
chatgptConnectorRouter.get('/oauth/authorize', (req: Request, res: Response) => {
  const clientId = (req.query.client_id as string) || '';
  const redirectUri = (req.query.redirect_uri as string) || '';
  const state = (req.query.state as string) || '';
  const scope = (req.query.scope as string) || 'mido:read mido:propose';
  const codeChallenge = (req.query.code_challenge as string) || '';
  const codeChallengeMethod = (req.query.code_challenge_method as string) || '';

  // Render a responsive, clean, dark-themed authorization consent screen
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Authorize ChatGPT — Mido AI</title>
  <link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    body {
      background: #090d16;
      color: #f1f5f9;
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 16px;
    }
    .card {
      background: rgba(17, 24, 39, 0.95);
      border: 1px solid rgba(99, 102, 241, 0.3);
      border-radius: 20px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.7);
      max-width: 480px;
      width: 100%;
      padding: 28px;
      position: relative;
      overflow: hidden;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: rgba(16, 185, 129, 0.15);
      border: 1px solid rgba(16, 185, 129, 0.3);
      color: #34d399;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      padding: 4px 10px;
      border-radius: 9999px;
      margin-bottom: 16px;
    }
    .title {
      font-size: 22px;
      font-weight: 800;
      color: #ffffff;
      margin-bottom: 8px;
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .subtitle {
      font-size: 13px;
      color: #94a3b8;
      line-height: 1.5;
      margin-bottom: 20px;
    }
    .scopes-box {
      background: rgba(0, 0, 0, 0.4);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 14px;
      padding: 16px;
      margin-bottom: 20px;
    }
    .scopes-title {
      font-size: 11px;
      text-transform: uppercase;
      font-weight: 700;
      color: #818cf8;
      margin-bottom: 10px;
    }
    .scope-item {
      display: flex;
      align-items: flex-start;
      gap: 10px;
      font-size: 12px;
      color: #cbd5e1;
      margin-bottom: 8px;
      line-height: 1.4;
    }
    .scope-item:last-child { margin-bottom: 0; }
    .icon { font-size: 15px; shrink: 0; }
    .privacy-notice {
      background: rgba(239, 68, 68, 0.1);
      border: 1px solid rgba(239, 68, 68, 0.25);
      border-radius: 12px;
      padding: 12px;
      font-size: 11px;
      color: #fca5a5;
      line-height: 1.4;
      margin-bottom: 24px;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .btn-group {
      display: flex;
      gap: 10px;
    }
    .btn {
      flex: 1;
      padding: 12px 18px;
      border-radius: 12px;
      font-size: 13px;
      font-weight: 700;
      cursor: pointer;
      text-align: center;
      text-decoration: none;
      transition: all 0.2s ease;
      border: none;
    }
    .btn-primary {
      background: linear-gradient(135deg, #6366f1, #8b5cf6);
      color: #ffffff;
      box-shadow: 0 4px 14px rgba(99, 102, 241, 0.4);
    }
    .btn-primary:hover {
      background: linear-gradient(135deg, #4f46e5, #7c3aed);
      transform: translateY(-1px);
    }
    .btn-secondary {
      background: rgba(255, 255, 255, 0.08);
      color: #94a3b8;
      border: 1px solid rgba(255, 255, 255, 0.1);
    }
    .btn-secondary:hover {
      background: rgba(255, 255, 255, 0.12);
      color: #f1f5f9;
    }
    .client-info {
      margin-top: 18px;
      font-size: 11px;
      color: #64748b;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="badge">
      <span>●</span> Official OAuth 2.0 Flow
    </div>
    
    <h1 class="title">
      <span>Connect ChatGPT</span>
      <span style="font-size: 16px; color: #818cf8;">⚡ Mido AI</span>
    </h1>
    
    <p class="subtitle">
      Authorize ChatGPT to inspect your Mido AI project architecture and propose improvements when you request help.
    </p>

    <div class="scopes-box">
      <div class="scopes-title">What ChatGPT will be able to do:</div>
      <div class="scope-item">
        <span class="icon">🔍</span>
        <div><strong>Inspect Architecture:</strong> Review frontend (React 19/Tailwind) and backend (Express/Cloud Run) technology stack.</div>
      </div>
      <div class="scope-item">
        <span class="icon">🎨</span>
        <div><strong>Review 24 Studios:</strong> Read active features like Mido Builder, Video Studio, and Humoris AI.</div>
      </div>
      <div class="scope-item">
        <span class="icon">🧩</span>
        <div><strong>List Tools & Plugins:</strong> View Spotify, Wolfram Alpha, Web Browser, and other registered plugins.</div>
      </div>
      <div class="scope-item">
        <span class="icon">💡</span>
        <div><strong>Propose Improvements:</strong> Submit code suggestions into your Mido AI review queue for your final approval.</div>
      </div>
    </div>

    <div class="privacy-notice">
      <span>🛡️</span>
      <div>
        <strong>Zero-Secrets Guarantee:</strong> Gemini API keys, Firebase credentials, Discord tokens, user passwords, and private chats are strictly redacted and NEVER accessible.
      </div>
    </div>

    <form method="POST" action="/oauth/authorize">
      <input type="hidden" name="client_id" value="${encodeURIComponent(clientId)}">
      <input type="hidden" name="redirect_uri" value="${encodeURIComponent(redirectUri)}">
      <input type="hidden" name="state" value="${encodeURIComponent(state)}">
      <input type="hidden" name="scope" value="${encodeURIComponent(scope)}">
      <input type="hidden" name="code_challenge" value="${encodeURIComponent(codeChallenge)}">
      <input type="hidden" name="code_challenge_method" value="${encodeURIComponent(codeChallengeMethod)}">
      
      <div class="btn-group">
        <button type="submit" name="action" value="deny" class="btn btn-secondary">Cancel</button>
        <button type="submit" name="action" value="approve" class="btn btn-primary">Authorize ChatGPT</button>
      </div>
    </form>

    <div class="client-info">
      Application: <strong>Mido AI Production</strong> • Client ID: <code>${clientId || 'mido-ai-client'}</code>
    </div>
  </div>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.send(html);
});

// User action handler on the consent screen
chatgptConnectorRouter.post('/oauth/authorize', (req: Request, res: Response) => {
  const { action, client_id, redirect_uri, state, scope, code_challenge, code_challenge_method } = req.body;

  const rawRedirectUri = redirect_uri ? decodeURIComponent(redirect_uri) : '';
  const decodedState = state ? decodeURIComponent(state) : '';

  if (action === 'deny') {
    if (rawRedirectUri) {
      const url = new URL(rawRedirectUri);
      url.searchParams.set('error', 'access_denied');
      url.searchParams.set('error_description', 'The user denied the authorization request.');
      if (decodedState) url.searchParams.set('state', decodedState);
      return res.redirect(url.toString());
    }
    return res.status(403).send('<h1>Authorization Denied</h1><p>You cancelled the ChatGPT connection.</p>');
  }

  // Generate a cryptographically secure 1-time authorization code
  const code = 'mido_code_' + crypto.randomBytes(16).toString('hex');
  const codeRecord: AuthCodeRecord = {
    code,
    clientId: client_id ? decodeURIComponent(client_id) : OAUTH_CLIENT_ID,
    redirectUri: rawRedirectUri,
    state: decodedState,
    scope: scope ? decodeURIComponent(scope) : 'mido:read mido:propose',
    codeChallenge: code_challenge ? decodeURIComponent(code_challenge) : undefined,
    codeChallengeMethod: code_challenge_method ? decodeURIComponent(code_challenge_method) : undefined,
    expiresAt: Date.now() + 10 * 60 * 1000 // 10 minutes expiry
  };

  authCodes.set(code, codeRecord);

  // If redirect_uri was provided by ChatGPT, redirect back to ChatGPT
  if (rawRedirectUri) {
    try {
      const url = new URL(rawRedirectUri);
      url.searchParams.set('code', code);
      if (decodedState) url.searchParams.set('state', decodedState);
      return res.redirect(url.toString());
    } catch {
      // Fallback if URL parsing failed
      const sep = rawRedirectUri.includes('?') ? '&' : '?';
      return res.redirect(`${rawRedirectUri}${sep}code=${encodeURIComponent(code)}${decodedState ? `&state=${encodeURIComponent(decodedState)}` : ''}`);
    }
  }

  // If accessed directly for testing without redirect_uri, show nice success page with code
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Authorization Approved — Mido AI</title>
  <style>
    body { background: #090d16; color: #f1f5f9; font-family: sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; padding: 20px; }
    .card { background: #111827; border: 1px solid rgba(16, 185, 129, 0.3); border-radius: 16px; padding: 24px; max-width: 500px; width: 100%; }
    h2 { color: #34d399; margin-bottom: 12px; }
    code { background: rgba(0,0,0,0.5); padding: 4px 8px; border-radius: 6px; color: #818cf8; word-break: break-all; display: block; margin: 12px 0; }
  </style>
</head>
<body>
  <div class="card">
    <h2>✓ Authorization Successful!</h2>
    <p>Your one-time authorization code has been issued:</p>
    <code>${code}</code>
    <p style="font-size: 13px; color: #94a3b8; margin-top: 10px;">
      When configured inside ChatGPT, ChatGPT will automatically exchange this code for an access token at <strong>/oauth/token</strong>.
    </p>
  </div>
</body>
</html>`);
});

// ----------------------------------------------------
// 3. OAUTH 2.0 TOKEN EXCHANGE ENDPOINT (POST)
// Standard RFC 6749 Token Endpoint
// ----------------------------------------------------
chatgptConnectorRouter.post('/oauth/token', (req: Request, res: Response) => {
  // Support both application/x-www-form-urlencoded and application/json
  const body = req.body || {};

  // Check HTTP Basic Authorization header for client_id:client_secret
  let clientId = body.client_id;
  let clientSecret = body.client_secret;

  const authHeader = req.headers.authorization;
  if (authHeader && authHeader.startsWith('Basic ')) {
    try {
      const decoded = Buffer.from(authHeader.slice(6), 'base64').toString('utf-8');
      const [bId, bSecret] = decoded.split(':');
      if (bId) clientId = bId;
      if (bSecret) clientSecret = bSecret;
    } catch {
      // Ignore basic auth decode error, fallback to body
    }
  }

  const grantType = body.grant_type;

  // Case A: authorization_code exchange
  if (grantType === 'authorization_code') {
    const code = body.code;
    if (!code) {
      return res.status(400).json({ error: 'invalid_request', error_description: 'Missing code parameter' });
    }

    const record = authCodes.get(code);
    if (!record) {
      return res.status(400).json({ error: 'invalid_grant', error_description: 'Authorization code is invalid or expired' });
    }

    if (Date.now() > record.expiresAt) {
      authCodes.delete(code);
      return res.status(400).json({ error: 'invalid_grant', error_description: 'Authorization code has expired' });
    }

    // PKCE code_verifier check if code_challenge was provided
    if (record.codeChallenge) {
      const codeVerifier = body.code_verifier;
      if (!codeVerifier) {
        return res.status(400).json({ error: 'invalid_grant', error_description: 'PKCE code_verifier required' });
      }
      if (record.codeChallengeMethod === 'S256') {
        const expectedChallenge = crypto.createHash('sha256').update(codeVerifier).digest('base64url');
        if (expectedChallenge !== record.codeChallenge) {
          return res.status(400).json({ error: 'invalid_grant', error_description: 'PKCE verification failed' });
        }
      } else if (codeVerifier !== record.codeChallenge) {
        return res.status(400).json({ error: 'invalid_grant', error_description: 'PKCE verification failed' });
      }
    }

    // Code is single use! Consume it immediately
    authCodes.delete(code);

    // Issue OAuth Access Token
    const accessToken = 'mido_oauth_at_' + crypto.randomBytes(24).toString('hex');
    const refreshToken = 'mido_oauth_rt_' + crypto.randomBytes(24).toString('hex');
    const expiresIn = 30 * 24 * 3600; // 30 days

    activeTokens.set(accessToken, {
      token: accessToken,
      clientId: record.clientId,
      scope: record.scope || 'mido:read mido:propose',
      createdAt: Date.now(),
      expiresAt: Date.now() + expiresIn * 1000,
      refreshToken
    });

    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('Pragma', 'no-cache');
    return res.json({
      access_token: accessToken,
      token_type: 'Bearer',
      expires_in: expiresIn,
      refresh_token: refreshToken,
      scope: record.scope || 'mido:read mido:propose'
    });
  }

  // Case B: refresh_token exchange
  if (grantType === 'refresh_token') {
    const refreshToken = body.refresh_token;
    if (!refreshToken) {
      return res.status(400).json({ error: 'invalid_request', error_description: 'Missing refresh_token parameter' });
    }

    // Find token with matching refresh_token
    let matchedToken: AccessTokenRecord | undefined;
    let oldAccessTokenKey: string | undefined;
    for (const [key, val] of activeTokens.entries()) {
      if (val.refreshToken === refreshToken) {
        matchedToken = val;
        oldAccessTokenKey = key;
        break;
      }
    }

    if (!matchedToken || !oldAccessTokenKey) {
      return res.status(400).json({ error: 'invalid_grant', error_description: 'Invalid refresh_token' });
    }

    // Invalidate old token
    activeTokens.delete(oldAccessTokenKey);

    // Issue new token
    const newAccessToken = 'mido_oauth_at_' + crypto.randomBytes(24).toString('hex');
    const newRefreshToken = 'mido_oauth_rt_' + crypto.randomBytes(24).toString('hex');
    const expiresIn = 30 * 24 * 3600;

    activeTokens.set(newAccessToken, {
      token: newAccessToken,
      clientId: matchedToken.clientId,
      scope: matchedToken.scope,
      createdAt: Date.now(),
      expiresAt: Date.now() + expiresIn * 1000,
      refreshToken: newRefreshToken
    });

    res.setHeader('Cache-Control', 'no-store');
    return res.json({
      access_token: newAccessToken,
      token_type: 'Bearer',
      expires_in: expiresIn,
      refresh_token: newRefreshToken,
      scope: matchedToken.scope
    });
  }

  // Case C: client_credentials (convenient for automated testing or headless ChatGPT agents)
  if (grantType === 'client_credentials') {
    const newAccessToken = 'mido_oauth_at_' + crypto.randomBytes(24).toString('hex');
    const expiresIn = 30 * 24 * 3600;

    activeTokens.set(newAccessToken, {
      token: newAccessToken,
      clientId: clientId || OAUTH_CLIENT_ID,
      scope: 'mido:read mido:propose',
      createdAt: Date.now(),
      expiresAt: Date.now() + expiresIn * 1000
    });

    res.setHeader('Cache-Control', 'no-store');
    return res.json({
      access_token: newAccessToken,
      token_type: 'Bearer',
      expires_in: expiresIn,
      scope: 'mido:read mido:propose'
    });
  }

  return res.status(400).json({
    error: 'unsupported_grant_type',
    error_description: `Grant type "${grantType}" is not supported. Supported: authorization_code, refresh_token, client_credentials`
  });
});

// OAuth Revocation endpoint (RFC 7009)
chatgptConnectorRouter.post('/oauth/revoke', (req: Request, res: Response) => {
  const token = req.body?.token;
  if (token) {
    activeTokens.delete(token);
    for (const [key, val] of activeTokens.entries()) {
      if (val.refreshToken === token) {
        activeTokens.delete(key);
      }
    }
  }
  res.status(200).json({ success: true, message: 'Token revoked successfully' });
});

// ----------------------------------------------------
// 4. OPENAPI 3.1.0 SPECIFICATION (Unauthenticated Discovery)
// Configured with OAuth 2.0 & Bearer Security Schemes
// ----------------------------------------------------
chatgptConnectorRouter.get('/api/openapi.json', (req: Request, res: Response) => {
  const serverUrl = getServerUrl(req);

  const openApiSpec = {
    openapi: '3.1.0',
    info: {
      title: 'Mido AI ChatGPT Connector API',
      description: 'Secure, authenticated connector enabling ChatGPT to inspect Mido AI architecture, review connected features, monitor system health, and propose authorized improvements.',
      version: '1.0.0',
      contact: {
        name: 'Mido AI Development Team',
        email: 'mido.gamez999@gmail.com'
      }
    },
    servers: [
      {
        url: serverUrl,
        description: 'Current Mido AI Host (Cloud Run / Local)'
      }
    ],
    paths: {
      '/api/connector/status': {
        get: {
          summary: 'Health & Authentication Validation',
          description: 'Validates that the connector token is recognized and returns server heartbeat status.',
          operationId: 'getConnectorStatus',
          security: [{ OAuth2: ['mido:read'] }, { BearerAuth: [] }],
          responses: {
            '200': {
              description: 'Successful validation',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      status: { type: 'string', example: 'connected' },
                      authenticated: { type: 'boolean', example: true },
                      serverTime: { type: 'string' },
                      appName: { type: 'string', example: 'Mido AI' }
                    }
                  }
                }
              }
            },
            '401': { description: 'Missing or invalid token' }
          }
        }
      },
      '/api/connector/architecture': {
        get: {
          summary: 'Inspect Mido AI Full Stack Architecture',
          description: 'Returns safe, sanitized technical architecture details of Mido AI (frameworks, models, databases, deployment). Secrets and keys are strictly redacted.',
          operationId: 'getAppArchitecture',
          security: [{ OAuth2: ['mido:read'] }, { BearerAuth: [] }],
          responses: {
            '200': {
              description: 'Architecture specifications',
              content: {
                'application/json': {
                  schema: { type: 'object' }
                }
              }
            }
          }
        }
      },
      '/api/connector/features': {
        get: {
          summary: 'List All 24 Mido AI Modes & Studios',
          description: 'Returns the catalogue of all 24 studio modes (Mido Builder, Video AI Studio, YouTube Studio, Music Studio, Humoris Friend, Face Detect, etc.).',
          operationId: 'getAppFeatures',
          security: [{ OAuth2: ['mido:read'] }, { BearerAuth: [] }],
          responses: {
            '200': {
              description: 'List of features and studios',
              content: {
                'application/json': {
                  schema: { type: 'object' }
                }
              }
            }
          }
        }
      },
      '/api/connector/plugins': {
        get: {
          summary: 'List Active & Installed Plugin Tools',
          description: 'Lists all ChatGPT-style tools (Spotify, Wolfram Alpha, Web Browser, Talking Tool, Python Sandbox, etc.) with parameters and sample queries.',
          operationId: 'getAppPlugins',
          security: [{ OAuth2: ['mido:read'] }, { BearerAuth: [] }],
          responses: {
            '200': {
              description: 'Plugins manifest and execution tools',
              content: {
                'application/json': {
                  schema: { type: 'object' }
                }
              }
            }
          }
        }
      },
      '/api/connector/app-state': {
        get: {
          summary: 'Get Live System Health & Runtime Metrics',
          description: 'Returns server uptime, memory utilization, environment specs, and storage status.',
          operationId: 'getAppState',
          security: [{ OAuth2: ['mido:read'] }, { BearerAuth: [] }],
          responses: {
            '200': {
              description: 'System health metrics',
              content: {
                'application/json': {
                  schema: { type: 'object' }
                }
              }
            }
          }
        }
      },
      '/api/connector/action/propose-improvement': {
        post: {
          summary: 'Propose Code or Feature Improvement',
          description: 'Submits an improvement proposal from ChatGPT into Mido AI pending user approval queue.',
          operationId: 'proposeImprovement',
          security: [{ OAuth2: ['mido:propose'] }, { BearerAuth: [] }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['title', 'category', 'description', 'reason'],
                  properties: {
                    title: { type: 'string', example: 'Optimize Chat Streaming' },
                    category: {
                      type: 'string',
                      enum: ['feature', 'refactor', 'bugfix', 'performance', 'ui'],
                      example: 'performance'
                    },
                    description: { type: 'string', example: 'Improve WebSocket frame dispatch latency.' },
                    suggestedCodeSnippet: { type: 'string' },
                    reason: { type: 'string', example: 'Reduces TTFT from 80ms to 24ms.' }
                  }
                }
              }
            }
          },
          responses: {
            '200': {
              description: 'Proposal recorded and queued for user approval',
              content: {
                'application/json': {
                  schema: { type: 'object' }
                }
              }
            }
          }
        }
      }
    },
    components: {
      securitySchemes: {
        OAuth2: {
          type: 'oauth2',
          description: 'Official OAuth 2.0 flow for ChatGPT Custom Actions & MCP clients.',
          flows: {
            authorizationCode: {
              authorizationUrl: `${serverUrl}/oauth/authorize`,
              tokenUrl: `${serverUrl}/oauth/token`,
              scopes: {
                'mido:read': 'Read Mido AI architecture, studios, plugins, and health telemetry.',
                'mido:propose': 'Submit improvement proposals for user confirmation.'
              }
            }
          }
        },
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT or API Key',
          description: 'Alternative direct authentication: Provide the Mido AI Connector Key.'
        }
      }
    }
  };

  res.json(openApiSpec);
});

// ----------------------------------------------------
// 5. CHATGPT PLUGIN MANIFEST (Standard RFC Discovery)
// ----------------------------------------------------
chatgptConnectorRouter.get('/.well-known/ai-plugin.json', (req: Request, res: Response) => {
  const serverUrl = getServerUrl(req);

  res.json({
    schema_version: 'v1',
    name_for_human: 'Mido AI Assistant Connector',
    name_for_model: 'mido_ai_connector',
    description_for_human: 'Securely inspect Mido AI architecture, review tools, and propose collaborative improvements.',
    description_for_model: 'Connector for Mido AI: Access architecture details, 24 studio tools, active plugins, system telemetry, and submit approved feature suggestions.',
    auth: {
      type: 'oauth',
      instructions: 'Authorize via Mido AI OAuth screen',
      client_url: `${serverUrl}/oauth/authorize`,
      scope: 'mido:read mido:propose',
      authorization_url: `${serverUrl}/oauth/token`,
      authorization_content_type: 'application/json',
      verification_tokens: {
        openai: 'mido_verified_openai_link'
      }
    },
    api: {
      type: 'openapi',
      url: `${serverUrl}/api/openapi.json`
    },
    logo_url: `${serverUrl}/assets/favicon.svg`,
    contact_email: 'mido.gamez999@gmail.com',
    legal_info_url: `${serverUrl}`
  });
});

// ----------------------------------------------------
// 6. CONNECTOR METADATA & CONFIG (For Mido AI Settings UI)
// ----------------------------------------------------
chatgptConnectorRouter.get('/api/connector/oauth-config', (req: Request, res: Response) => {
  const serverUrl = getServerUrl(req);
  res.json({
    serverUrl,
    authType: 'oauth_or_api_key',
    oauth: {
      clientId: OAUTH_CLIENT_ID,
      clientSecret: OAUTH_CLIENT_SECRET,
      authorizationUrl: `${serverUrl}/oauth/authorize`,
      tokenUrl: `${serverUrl}/oauth/token`,
      scope: 'mido:read mido:propose',
      tokenExchangeMethod: 'Default (POST body)',
      discoveryUrl: `${serverUrl}/.well-known/oauth-authorization-server`
    },
    apiKeyAuth: {
      type: 'Bearer',
      currentKey: currentMidoApiKey,
      testSeedToken: DEFAULT_SEED_TOKEN,
      openapiUrl: `${serverUrl}/api/openapi.json`
    },
    mcp: {
      remoteEndpoint: `${serverUrl}/api/mcp`,
      messagesEndpoint: `${serverUrl}/api/mcp/messages`,
      protocol: 'MCP JSON-RPC 2.0 (2024-11-05)'
    },
    activeTokensCount: activeTokens.size,
    pendingProposalsCount: pendingProposals.filter(p => p.status === 'pending').length
  });
});

// Key regeneration endpoint (callable from Mido AI Settings UI)
chatgptConnectorRouter.post('/api/connector/regenerate-key', (req: Request, res: Response) => {
  currentMidoApiKey = 'mido_key_live_' + crypto.randomBytes(12).toString('hex');
  res.json({
    success: true,
    newApiKey: currentMidoApiKey,
    message: 'Mido AI Connector Key regenerated successfully.'
  });
});

// ----------------------------------------------------
// 7. AUTHENTICATED INSPECTION ENDPOINTS
// ----------------------------------------------------

// Status & Authentication Verification
chatgptConnectorRouter.get('/api/connector/status', verifyConnectorAuth, (req: Request, res: Response) => {
  const authInfo = (req as any).connectorAuth || {};
  res.json({
    status: 'connected',
    authenticated: true,
    authMethod: authInfo.type === 'oauth' ? 'OAuth 2.0 Access Token' : 'Mido AI Connector Key',
    connectorVersion: '2.0.0',
    serverTime: new Date().toISOString(),
    uptimeSeconds: Math.floor(process.uptime()),
    appName: 'Mido AI',
    userEmail: 'mido.gamez999@gmail.com',
    securityStatus: 'Authenticated 🔐',
    readOnlyGuaranteed: true,
    secretsMasked: true
  });
});

// Full Architecture Specification (Strictly Sanitized)
chatgptConnectorRouter.get('/api/connector/architecture', verifyConnectorAuth, (_req: Request, res: Response) => {
  res.json({
    appName: 'Mido AI',
    edition: 'Insane Production Edition V4.0',
    frontend: {
      framework: 'React 19 (SPA)',
      language: 'TypeScript 5.8',
      bundler: 'Vite 6.2 with React plugin',
      styling: 'Tailwind CSS v4 with glassmorphism, responsive mobile-first UI',
      icons: 'Lucide React'
    },
    backend: {
      runtime: 'Node.js (TypeScript via tsx & esbuild)',
      framework: 'Express.js 4.21',
      port: 3000,
      protocol: 'HTTPS via Cloud Run',
      staticServing: 'Vite middleware in dev, bundled CJS in production',
      endpointsCount: 45
    },
    aiEngine: {
      primaryProvider: 'Google Gemini via @google/genai SDK',
      defaultModel: 'gemini-3.8-flash',
      fallbackChains: ['gemini-flash-latest', 'gemini-3.1-flash-lite', 'gemini-3.1-pro-preview'],
      webGrounding: 'Google Search grounding with live web citations',
      codeGeneration: 'Dynamic HTML/CSS/JS sandbox generation with live previews',
      apiKeyStatus: '[PROTECTED_SERVER_SIDE]' // Key never exposed
    },
    database: {
      provider: 'Google Cloud Firestore',
      firestoreDatabaseId: 'ai-studio-midoai-c83beca6-937e-467c-9aa9-4481da513969',
      credentialsStatus: '[PROTECTED_SERVER_SIDE]'
    },
    clientStorage: {
      driver: 'Browser LocalStorage',
      keys: [
        'mido_ai_messages_v1',
        'mido_chat_sessions_v1',
        'mido_permanent_memories_v1',
        'mido_chatgpt_plugins_v2',
        'mido_saved_apps_v1',
        'mido_app_settings_v1',
        'mido_humoris_msgs_v2'
      ]
    },
    securityPolicies: {
      geminiApiKey: 'SERVER_ONLY_NEVER_EXPOSED',
      firebaseCredentials: 'SERVER_ONLY_NEVER_EXPOSED',
      discordTokens: 'LOCAL_ENCRYPTED_NEVER_EXPOSED',
      youtubeDataApiKey: 'SERVER_ONLY_NEVER_EXPOSED',
      userPasswordsAndChats: 'PRIVATE_CLIENT_DATA_RESTRICTED'
    }
  });
});

// All 24 Studio Modes & Features
chatgptConnectorRouter.get('/api/connector/features', verifyConnectorAuth, (_req: Request, res: Response) => {
  res.json({
    totalStudios: 24,
    studios: [
      { id: 'chat', name: 'Mido AI Chat', description: 'ChatGPT-style chat with live search grounding, link styling, and tool calling.' },
      { id: 'app-studio', name: 'Mido Builder 🚀', description: 'Interactive AI web app & site builder with real-time preview and export.' },
      { id: 'humoris', name: 'Humoris Human Best Friend', description: 'Real human friend companion AI with unfiltered banter, roasts, and debates.' },
      { id: 'video-studio', name: 'Video Studio AI', description: 'AI video generation and rendering powered by Veo and json2video.' },
      { id: 'photo-studio', name: 'Photo Studio AI', description: 'AI image generator, upscaler, and style transfer.' },
      { id: 'music-studio', name: 'Music Studio', description: 'Synthesizer, chord progression maker, and beat creator.' },
      { id: 'youtube-studio', name: 'YouTube Studio', description: 'Live channel statistics, video analysis, and script generator.' },
      { id: 'talking-avatar', name: 'Talking Avatar', description: 'Animated character speech animator with lip-sync synthesis.' },
      { id: 'discord-studio', name: 'Discord Bot Studio', description: 'Discord bot generator, slash commands, and webhook dispatcher.' },
      { id: 'organisation', name: 'Organisation & Habit Hub', description: 'Task checklists, daily routines, and productivity trackers.' },
      { id: 'face-detect', name: 'Face Detect Vision', description: 'Real-time face detection, bounding boxes, and pose analysis.' },
      { id: 'voice-responding', name: 'Voice Responding', description: '2-way interactive voice conversation with ultra-low latency.' },
      { id: 'mido-video-ai', name: 'Mido Video AI', description: 'Prompt-to-video diffusion studio with scene controls.' },
      { id: 'mido-ear', name: 'Mido Ear Audio', description: 'Spatial audio visualizer and audio frequency breakdown.' },
      { id: 'mido-orb', name: 'Mido Orb 3D', description: 'Three.js interactive 3D particle sphere canvas.' },
      { id: 'mido-nemis', name: 'Mido Nemis', description: 'Cyberpunk system diagnostic and performance monitor.' },
      { id: 'champions-studio', name: 'Champions League Studio', description: 'Live football scores, standings, and match predictions.' },
      { id: 'facebook-studio', name: 'Social Media Studio', description: 'Viral social post and caption copywriter.' },
      { id: 'editor-studio', name: 'Mido Code Editor', description: 'Syntax highlighting, multi-file code workspace.' },
      { id: 'under-the-sphere', name: 'Under The Sphere', description: 'Immersive 3D audio-reactive sphere visualization.' },
      { id: 'hello-mido-calls', name: 'Hello Mido Calls', description: 'Voice call simulator with custom personality voices.' },
      { id: 'mido-shortcuts', name: 'Mido Shortcuts', description: 'Global command palette and hotkey triggers.' },
      { id: 'mido-guide', name: 'App Guide & Manual', description: 'Interactive documentation and feature tutorials.' },
      { id: 'promo-studio', name: 'Promo Video Studio', description: 'Commercials and marketing clip generator.' }
    ]
  });
});

// Active & Installed Plugins List
chatgptConnectorRouter.get('/api/connector/plugins', verifyConnectorAuth, (_req: Request, res: Response) => {
  res.json({
    pluginArchitecture: 'ChatGPT Plugin & Tool Specification',
    maxConcurrentActivePlugins: 3,
    registeredPlugins: [
      {
        id: 'talking-tool',
        name: 'Mido Talking Tool',
        icon: '🎙️',
        category: 'tools',
        brandColor: '#A855F7',
        capabilities: ['neural_speech_synthesis', 'audio_waveform', 'voice_readout'],
        status: 'Active & Verified'
      },
      {
        id: 'spotify',
        name: 'Spotify Music',
        icon: '🎵',
        category: 'media',
        brandColor: '#1DB954',
        capabilities: ['track_search', 'audio_preview', 'synchronized_lyrics'],
        status: 'Active & Verified'
      },
      {
        id: 'wolfram',
        name: 'Wolfram Alpha',
        icon: '🧮',
        category: 'math',
        brandColor: '#DD1100',
        capabilities: ['step_by_step_calculus', 'physics_formulas', 'scientific_data'],
        status: 'Active & Verified'
      },
      {
        id: 'web-browser',
        name: 'Web Browser & Search',
        icon: '🌐',
        category: 'popular',
        brandColor: '#0EA5E9',
        capabilities: ['live_web_indexing', 'source_grounding', 'favicon_extraction'],
        status: 'Active & Verified'
      },
      {
        id: 'code-interpreter',
        name: 'Python Code Sandbox',
        icon: '💻',
        category: 'developer',
        brandColor: '#3B82F6',
        capabilities: ['python_virtual_execution', 'data_charting', 'math_computation'],
        status: 'Installed'
      },
      {
        id: 'youtube-scout',
        name: 'YouTube Scout',
        icon: '▶️',
        category: 'media',
        brandColor: '#EF4444',
        capabilities: ['video_discovery', 'channel_metrics', 'transcript_summary'],
        status: 'Installed'
      },
      {
        id: 'amazon-deals',
        name: 'Amazon Shopping Deals',
        icon: '📦',
        category: 'shopping',
        brandColor: '#F59E0B',
        capabilities: ['price_tracking', 'verified_ratings', 'deal_finder'],
        status: 'Installed'
      },
      {
        id: 'google-maps',
        name: 'Google Maps Route Matrix',
        icon: '📍',
        category: 'travel',
        brandColor: '#10B981',
        capabilities: ['turn_by_turn_eta', 'distance_matrix', 'traffic_prediction'],
        status: 'Installed'
      }
    ]
  });
});

// Live System Health & Runtime Metrics
chatgptConnectorRouter.get('/api/connector/app-state', verifyConnectorAuth, (_req: Request, res: Response) => {
  const memoryUsage = process.memoryUsage();
  res.json({
    uptimeSeconds: Math.floor(process.uptime()),
    nodeVersion: process.version,
    platform: process.platform,
    arch: process.arch,
    cpuCount: os.cpus().length,
    systemLoad: os.loadavg(),
    memory: {
      rssMb: Math.round(memoryUsage.rss / 1024 / 1024),
      heapTotalMb: Math.round(memoryUsage.heapTotal / 1024 / 1024),
      heapUsedMb: Math.round(memoryUsage.heapUsed / 1024 / 1024)
    },
    activeAIProvider: 'Google Gemini (Native Node.js SDK)',
    activeTokensCount: activeTokens.size,
    pendingProposalsCount: pendingProposals.filter(p => p.status === 'pending').length
  });
});

// Authorized Action: Propose an Improvement
chatgptConnectorRouter.post('/api/connector/action/propose-improvement', verifyConnectorAuth, (req: Request, res: Response) => {
  const { title, category, description, suggestedCodeSnippet, reason } = req.body;

  if (!title || !description) {
    return res.status(400).json({
      error: 'Bad Request',
      message: 'Fields "title" and "description" are required.'
    });
  }

  const newProposal: ChatGPTProposal = {
    id: `prop_${Date.now()}`,
    timestamp: new Date().toISOString(),
    title: String(title).slice(0, 100),
    category: ['feature', 'refactor', 'bugfix', 'performance', 'ui'].includes(category) ? category : 'feature',
    description: String(description).slice(0, 1000),
    suggestedCodeSnippet: suggestedCodeSnippet ? String(suggestedCodeSnippet).slice(0, 3000) : undefined,
    reason: reason ? String(reason).slice(0, 500) : 'ChatGPT collaboration recommendation',
    status: 'pending'
  };

  pendingProposals.unshift(newProposal);

  res.json({
    success: true,
    proposalId: newProposal.id,
    status: 'pending_user_approval',
    message: `Proposal "${newProposal.title}" successfully recorded and queued in Mido AI for user confirmation.`,
    proposal: newProposal
  });
});

// List Proposals (for Mido AI Settings UI)
chatgptConnectorRouter.get('/api/connector/proposals', (req: Request, res: Response) => {
  res.json({
    count: pendingProposals.length,
    proposals: pendingProposals
  });
});

// Approve Proposal (from Mido AI UI)
chatgptConnectorRouter.post('/api/connector/proposals/:id/approve', (req: Request, res: Response) => {
  const proposal = pendingProposals.find(p => p.id === req.params.id);
  if (!proposal) {
    return res.status(404).json({ error: 'Proposal not found' });
  }
  proposal.status = 'approved';
  res.json({ success: true, message: `Proposal "${proposal.title}" approved!`, proposal });
});

// Reject Proposal (from Mido AI UI)
chatgptConnectorRouter.post('/api/connector/proposals/:id/reject', (req: Request, res: Response) => {
  const proposal = pendingProposals.find(p => p.id === req.params.id);
  if (!proposal) {
    return res.status(404).json({ error: 'Proposal not found' });
  }
  proposal.status = 'rejected';
  res.json({ success: true, message: `Proposal "${proposal.title}" rejected.`, proposal });
});

// ----------------------------------------------------
// 8. MODEL CONTEXT PROTOCOL (MCP) INTERFACE
// Remote JSON-RPC 2.0 interface compliant with MCP specification
// ----------------------------------------------------
async function handleMcpRequest(req: Request, res: Response) {
  const { jsonrpc, id, method, params } = req.body;

  if (jsonrpc !== '2.0') {
    return res.status(400).json({
      jsonrpc: '2.0',
      id: id || null,
      error: { code: -32600, message: 'Invalid Request: jsonrpc must be "2.0"' }
    });
  }

  switch (method) {
    case 'initialize': {
      return res.json({
        jsonrpc: '2.0',
        id,
        result: {
          protocolVersion: '2024-11-05',
          capabilities: {
            tools: {},
            resources: {}
          },
          serverInfo: {
            name: 'mido-ai-connector',
            version: '2.0.0'
          }
        }
      });
    }

    case 'tools/list': {
      return res.json({
        jsonrpc: '2.0',
        id,
        result: {
          tools: [
            {
              name: 'inspect_architecture',
              description: 'Inspect full Mido AI technology stack, frameworks, database, and models.',
              inputSchema: { type: 'object', properties: {} }
            },
            {
              name: 'list_app_features',
              description: 'Retrieve all 24 Mido AI studios, tools, and visual modes.',
              inputSchema: { type: 'object', properties: {} }
            },
            {
              name: 'list_installed_plugins',
              description: 'List all ChatGPT plugins and API tools registered in Mido AI.',
              inputSchema: { type: 'object', properties: {} }
            },
            {
              name: 'get_system_health',
              description: 'Read runtime uptime, memory utilization, and server metrics.',
              inputSchema: { type: 'object', properties: {} }
            },
            {
              name: 'propose_improvement',
              description: 'Submit an improvement proposal to Mido AI pending user approval.',
              inputSchema: {
                type: 'object',
                required: ['title', 'description'],
                properties: {
                  title: { type: 'string' },
                  category: { type: 'string', enum: ['feature', 'refactor', 'bugfix', 'performance', 'ui'] },
                  description: { type: 'string' },
                  suggestedCodeSnippet: { type: 'string' }
                }
              }
            }
          ]
        }
      });
    }

    case 'tools/call': {
      const toolName = params?.name;
      const toolArgs = params?.arguments || {};

      switch (toolName) {
        case 'inspect_architecture': {
          return res.json({
            jsonrpc: '2.0',
            id,
            result: {
              content: [
                {
                  type: 'text',
                  text: JSON.stringify({
                    appName: 'Mido AI',
                    frontend: 'React 19 + TypeScript + Vite + Tailwind CSS v4',
                    backend: 'Node.js Express on Cloud Run (Port 3000)',
                    aiEngine: 'Google Gemini 3.8 Flash SDK (Server-Side)',
                    database: 'Firestore (ai-studio-midoai-c83beca6-937e-467c-9aa9-4481da513969)',
                    security: 'Tokens & API keys strictly encrypted and masked'
                  }, null, 2)
                }
              ]
            }
          });
        }

        case 'list_app_features': {
          return res.json({
            jsonrpc: '2.0',
            id,
            result: {
              content: [
                {
                  type: 'text',
                  text: 'Mido AI includes 24 studio modes: Mido Builder (website generator), Video AI Studio (Veo + json2video), Photo Studio, Music Studio, Humoris Best Friend AI, YouTube Studio, Talking Avatar, Discord Bot Studio, and Organisation Hub.'
                }
              ]
            }
          });
        }

        case 'list_installed_plugins': {
          return res.json({
            jsonrpc: '2.0',
            id,
            result: {
              content: [
                {
                  type: 'text',
                  text: 'Installed Plugins: 1. Mido Talking Tool (Neural Speech), 2. Spotify Music, 3. Wolfram Alpha, 4. Web Browser & Search, 5. Python Sandbox, 6. YouTube Scout, 7. Amazon Deals, 8. Google Maps.'
                }
              ]
            }
          });
        }

        case 'get_system_health': {
          const mem = process.memoryUsage();
          return res.json({
            jsonrpc: '2.0',
            id,
            result: {
              content: [
                {
                  type: 'text',
                  text: `Status: Online. Uptime: ${Math.floor(process.uptime())}s. Heap Used: ${Math.round(mem.heapUsed / 1024 / 1024)}MB. Node: ${process.version}.`
                }
              ]
            }
          });
        }

        case 'propose_improvement': {
          const propTitle = toolArgs.title || 'Untitled Proposal';
          const propDesc = toolArgs.description || 'No description provided';
          const proposal: ChatGPTProposal = {
            id: `mcp_${Date.now()}`,
            timestamp: new Date().toISOString(),
            title: propTitle,
            category: toolArgs.category || 'feature',
            description: propDesc,
            suggestedCodeSnippet: toolArgs.suggestedCodeSnippet,
            reason: 'Submitted via MCP Remote Tool Calling',
            status: 'pending'
          };
          pendingProposals.unshift(proposal);

          return res.json({
            jsonrpc: '2.0',
            id,
            result: {
              content: [
                {
                  type: 'text',
                  text: `Success! Proposal "${propTitle}" (ID: ${proposal.id}) was safely queued in Mido AI.`
                }
              ]
            }
          });
        }

        default:
          return res.status(404).json({
            jsonrpc: '2.0',
            id,
            error: { code: -32601, message: `Method or tool "${toolName}" not found` }
          });
      }
    }

    case 'resources/list': {
      return res.json({
        jsonrpc: '2.0',
        id,
        result: {
          resources: [
            { uri: 'mido://architecture', name: 'Mido AI Full Architecture', mimeType: 'application/json' },
            { uri: 'mido://features', name: 'Mido AI 24 Studio Modes', mimeType: 'application/json' },
            { uri: 'mido://plugins', name: 'ChatGPT Plugins Specification', mimeType: 'application/json' },
            { uri: 'mido://health', name: 'Live Runtime Health', mimeType: 'application/json' }
          ]
        }
      });
    }

    default:
      return res.status(400).json({
        jsonrpc: '2.0',
        id,
        error: { code: -32601, message: `Unrecognized method "${method}"` }
      });
  }
}

chatgptConnectorRouter.post('/api/mcp', verifyConnectorAuth, handleMcpRequest);
chatgptConnectorRouter.post('/api/mcp/messages', verifyConnectorAuth, handleMcpRequest);
